version: "3"
services:
  app:
    image: political:1.0
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/politicalmanagement
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
  db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=politicalmanagement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres